{% set name = "napari-workshop-plugin" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-workshop-plugin-{{ version }}.tar.gz
  sha256: dd60dcbb682f937926a11a0819cc91139207ad95142ff0265b8120acaf2ce110

build:
  noarch: python
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools >=42.0.0
    - wheel
    - setuptools-scm
    - pip
  run:
    - python
    - numpy <2,>=1.23
    - magicgui ==0.7.3
    - qtpy ==2.3.1

test:
  imports:
    - napari_workshop_plugin[testing]
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A plugin to demonstrate some concepts from the 2023 workshop on software development related to napari
  description: |
    A plugin to demonstrate some concepts from the 2023 workshop on software development related to napari.
  license: MIT
  license_file: LICENSE
  doc_url: https://seankmartin.github.io/napari-software-development-workshop/

extra:
  recipe-maintainers:
    - seankmartin
